# Generated by Django 3.1.1 on 2020-09-18 23:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('image', models.ImageField(help_text='Boyut = 1170x540', upload_to='products/', verbose_name='Kapak Resmi')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('youtube_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Youtube Link')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınla')),
                ('sorting', models.IntegerField(verbose_name='Sıralama')),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_p', to='product.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Resim Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Resim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Resim',
                'verbose_name_plural': 'Resimler',
            },
        ),
    ]
