# Generated by Django 3.1.1 on 2020-09-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Adı Soyadı')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Okundu', 'Okundu'), ('Kapandı', 'Kapandı')], default='Yeni', max_length=10, verbose_name='Mesaj Durumu')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Yönetici Notu')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Resim Adı')),
                ('image', models.ImageField(help_text='Önerilen Boyutlar : 1170 x 450', upload_to='contacts/', verbose_name='Ofis Resimleri')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlama')),
            ],
            options={
                'verbose_name': 'Ofis Resim',
                'verbose_name_plural': 'Ofis Resimleri',
            },
        ),
    ]
