# Generated by Django 3.1.1 on 2020-09-19 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Haber Başlık')),
                ('image', models.ImageField(help_text='Boyutlar: 1200x500', upload_to='blogs/', verbose_name='Blog Resmi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Haber İçerik')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['created_date'],
            },
        ),
    ]
