# Generated by Django 3.1.1 on 2020-09-19 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hakkımızda Başlık')),
                ('short_description', models.TextField(help_text='Bu metin sadece anasayfada gözükür', verbose_name='Anasayfa Hakkımızda')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Hakkımızda Metni')),
                ('image_1', models.ImageField(help_text='Önerilen boyutlar: 164x148', upload_to='abouts/', verbose_name='Resim 1')),
                ('image_2', models.ImageField(help_text='Önerilen boyutlar: 212x186', upload_to='abouts/', verbose_name='Resim 2')),
                ('image_3', models.ImageField(help_text='Önerilen boyutlar: 318x288', upload_to='abouts/', verbose_name='Resim 3')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='BüYÜK HARFLE YAZIN', max_length=50, verbose_name='Başlık')),
                ('description', models.CharField(help_text='Maximum 145 karakter', max_length=145, verbose_name='Açıklama')),
                ('is_published', models.BooleanField(default=True)),
                ('sorting', models.IntegerField(verbose_name='Sıralama')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Bilgi',
                'verbose_name_plural': 'Bilgiler',
                'ordering': ['sorting'],
            },
        ),
    ]
